my: 
    greeting: "Hello, Name_yml"
    list.values: "1,2,3"
    map.values: "{sfn:'Anushree', sln:'Kashyap'}"
db: 
    connection: oracle
    hostName: xe
    port: 2022
management.endpoints.web.exposure.include: "*"

# to make profile active
spring.profiles.active: testY